server:
  port: 8080

mysql:
  dsn: root:123456@tcp(127.0.0.1:3306)/nbgo?charset=utf8mb4&parseTime=True&loc=Local
  maxIdleConns: 100 # 最多空闲连接数
  maxOpenConns: 100 # 最多连接数

redis:
  url: localhost:6379
  password: 123456

jwt:
  expiresAt: 30
  signingKey: nbgo

mode:
  develop: false

log:
  MaxSize: 1 # 日志文件最大尺寸
  MaxBackups: 10 #保留旧文件最大个数
  MaxAge: 28 #保留旧文件最大天数